In [1]:
import numpy as np
from scipy.optimize import brentq
import encoder
import decoder
from matplotlib import pyplot as plt
%matplotlib inline

In [58]:
enc = encoder.PolarCodeAWGN(4/4, 0.2, 8, 4)

In [42]:
enc.zvalues

array([ 0.05425336,  0.56453826,  0.82336423,  4.        ])

In [75]:
enc.frozen_indices

array([7, 4, 5, 6])

In [71]:
msg = np.array([1, 0, 1, 1])

In [72]:
cw = enc.encode(msg)
cw

array([ 1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.])

In [73]:
enc.decode(cw.astype(int), 1)[enc.indices]

[0, 0, 1, 0, 0, 0, 0, 0]


/home/aplavin/work/decoder.py:149: RuntimeWarning: invalid value encountered in double_scalars
  P_lambd[beta][p]=P_lambd[beta][p]/sigma;


array([ 1.,  0.,  0.,  1.])